### ISSUE TITLE
Products gone after update?

### ISSUE THREAD

**Issue by krebbi** [VividWeb/vivid_store#195] opened 2015-09-17 09:52 UTC
Is it intended that after an update all products are deleted?

**Comment by brucewyne** [comment] 2015-09-17 12:33
Frankly - no. To what version did you upgrade? From which? Add more products, run the upgrade script again by going to example.com/index.php/dashboard/extend/update/do_update/vivid_store - do they go away again?

**Comment by krebbi** [comment] 2015-09-21 11:51
can't test it. need to wait for your code cleanup to be finished. 

![bildschirmfoto 2015-09-21 um 13 50 31](https://cloud.githubusercontent.com/assets/3884521/9991156/c8683ec8-6067-11e5-9947-41906b48b10e.png)

**Comment by Mesuva** [comment] 2015-09-22 12:03
I can confirm this is still happening, just hit this myself with up-to-date code

**Comment by brucewyne** [comment] 2015-09-22 15:06
that's scary.

**Comment by Mesuva** [comment] 2015-09-22 22:57
I can't quite put my finger on it why it's happening.
I had to do an update yesterday because I found some database table was missing a field.
I just incremented the package version in it's controller and triggered the update via the dashboard.
(just tried it again)

All tables controlled by the db.xml file are then emptied. It's only tables that are created via Doctrine that remain populated.

**Comment by julehti** [comment] 2015-09-23 07:39
This happened also to me. All products and groups were disappeared after v. 3.0.1 update.

**Comment by brucewyne** [comment] 2015-09-23 14:57
This has been fixed in the latest version of C5 (in git). Either I need to migrate many functions into the installer, or I've found another reason to move everything to ORM. Good lord.

**Comment by krebbi** [comment] 2015-09-24 10:16
but why are other settings still there like the currency-stuff but the products, discounts, orders, ..  are gone?

**Comment by julehti** [comment] 2015-09-24 10:21
Same happened to me: settings were left but products were gone. Is there an significance, if you are moving store pages to another place in your C5 page hierachy?

**Comment by brucewyne** [comment] 2015-09-24 12:23
@krebbi @julehti - it's a known issue I raised to C5. C5 keeps all the Config settings as well as all the database items managed by ORM entities. As of 3.0.1, only Shipping and Tax are managed by ORM. So any other custom database tables get wiped. C5 incorrectly assumes if you're using an ORM, then you're using it for everything and it will wipe all other custom tables.

**Comment by krebbi** [comment] 2015-09-24 14:09
hmm.. and could be the easier solution to move verything into ORM in the vividstore instead of waiting for portland to publish a new update? 
regardless of this, wouldn't it a better style to have all DB-stuff in one place? ;)

**Comment by brucewyne** [comment] 2015-09-24 14:17
@krebbi that is actually what is happening now. If you look at the Product stuff in /src/ its wildly cleaned up, broken into more appropriate classes, and all done in ORM. 

Also, obviously, the Product interface is likely broken until that's complete.

**Comment by krebbi** [comment] 2015-09-25 13:50
may I ask why you guys commit code which is broken? Like right now trying to add a product results in: 

Whoops\Exception\ErrorException thrown with message "Cannot redeclare Concrete\Package\VividStore\Src\VividStore\Product\Product::save()"

Stacktrace:
#0  in /public/packages/vivid_store/src/VividStore/Product/Product.php:335

and with such errors I'm asking myself if I need to open an issue or not, because they are so obvious?
I don't want to sound rude and this is a serious question.

**Comment by brucewyne** [comment] 2015-09-25 17:26
That's probably a good question. The work I'm currently doing in the product class is pretty extensive, and following the rule to commit often, commit often is still hundreds of lines of changes. For such a long project, I should probably make a new branch, and I likely will next major class I work on after Product.

**Comment by Mesuva** [comment] 2016-01-13 21:44
I believe this was an error more relating to concrete5 than vivid_store, quite a few c5 versions ago. So I'm closing this for now.

**Closed as completed by Mesuva** 2016-01-13 21:44 UTC
